name: Publish Website to Cpanel
on:
  push:
    branches:
      - master

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: deploy
      steps:
        - name: Checkout
          uses: actions/checkout@v2.1.0
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: public_html/prueba2.networking.miami
            local_path: './static/*'
            remote_path: '/public_html/prueba2.networking.miami'

